### ISSUE TITLE
Deduper Peer Review

### ISSUE THREAD

**Issue by julhays** [Mahmoud-56/Deduper-Mahmoud-56#1]
Hi Mahmoud,

Your problem statement is very detailed so I can clearly understand what you are trying to do. One suggestion here is when you say "PCR duplicates should map to the same 5' start of read" that is not always true because the POS field gives the position of the leftmost end of the read (which is the 5' for the + strand and the 3' end for the - strand).

Your algorithm makes a lot of sense to me and I can follow the logic clearly. I like your idea of using a set to store the unique read information. It is also good that you clear it each time you encounter a new chromosome, which will save you memory. The only piece that is confusing to me is the "adjust the start position based on the strand direction". I could be wrong, but I believe the adjusted start position is just the POS number - the number of clipped nts (the number in front of the S in the CIGAR string). Does the strandedness change how you deal with this? One other suggestion is since you are going to have a new set for each chromosome, you probably don't need to store the chromosome information in each individual tuple. You could just have it as a global variable instead.

I believe your algorithm does everything it's supposed to do outlined in part 1. Good job!

Your functions all seem reasonable as well. The find_UMI one is a good idea because I did not consider how I will extract the UMI from the NAME field. Will the find_pos function make the adjustment to the POS based on soft clipping?

Overall, I think you have a great strategy. Good luck coding this up!

-Jules

**Comment by Mahmoud-56** [comment]
Hi Jules, 

Thank you for the constructive feedback. Initially, I was not thinking of the - strand when I wrote the introduction. You are right POS will be the 5' only for the + strand. For adjusting POS based on strand direction, the way I understood it is that we will be looking at the number before S in the CIGAR string (only on the left side) and adjusting the POS by subtracting that number from POS and that's for for the + strand, but for the - strand, we should add the Ms and S's on the right side end instead to get the correct 5' mapping position instead of POS given by the SAM file. For example, if you had 3S5M2S for the - strand, you would want to add 5 and 2 to the POS number to get the 5' mapping position. 

And so my find_pos function should account for soft clipping based on whether we have + or - strand. And I think we should be accounting for deletions but not insertions in the CIGAR string. Please let me know if you have other questions or if what I mentioned doesn't make sense.
